in:
  type: postgresql
  host: 35.239.223.162
  user: stitch_extract
  password: etl_101_passwd
  database: northwind
  table: categories
  column_options:
    picture: 
      value_type: string
    photo:
      value_type: string
out:
  type: stdout
